name: CI process
on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
          cache: gradle

      - name: Cache opencv jar and binary
        id: cache-opencv
        uses: actions/cache@v3
        env:
          cache-name: cache-opencv-artifacts
        with:
          path: ./opencv-artifact/
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-opencv.outputs.cache-hit != 'true' }}
        name: Build Opencv jar and binary
        continue-on-error: true
        shell: bash
        run: |
          sudo apt update && sudo apt install -y cmake g++ wget unzip
          wget -O opencv.zip https://github.com/opencv/opencv/archive/3.4.16.zip
          unzip opencv.zip
          sudo apt-get install -y ant
          mkdir -p buildOpencv && cd buildOpencv
          cmake -D BUILD_SHARED_LIBS=OFF ../opencv-3.4.16
          cmake --build .
          make -j
          echo "Moving jar and so file to opencv-artifact folder"
          mkdir -p ../opencv-artifact
          cp ./bin/opencv-3416.jar ../opencv-artifact/opencv_3416.jar
          cp ./lib/libopencv_java3416.so ../opencv-artifact/libopencv_java3416.so
          echo "Generated build artifacts details"
          ls ../opencv-artifact/

      - name: Archive opencv artifacts
        uses: actions/upload-artifact@v3
        with:
          name: opencv-3416
          path: |
            ./opencv-artifact/

      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Publish package
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: publish
        env:
          ENVIRONMENT: ${{ secrets.ENV }}
          GPR_USER: ${{ secrets.GPR_USER }}
          GPR_API_KEY: ${{ secrets.GPR_API_KEY }}

