name: CI process
on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          cache: gradle
      - name: Build Opencv jar and binary
        shell: bash
        run: |
          sudo apt update && sudo apt install -y cmake g++ wget unzip
          wget -O opencv.zip https://github.com/opencv/opencv/archive/3.4.16.zip
          unzip opencv.zip
          sudo apt-get install -y ant
          mkdir -p build && cd build
          cmake -D BUILD_SHARED_LIBS=OFF ../opencv-3.4.16
          cmake --build .
          make -j
          ls ./build/bin/
          ls ./build/lib/
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: clean build test

