name: CI process
on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          cache: gradle

      - name: Cache OpenCV
        id: opencv-cache
        uses: actions/cache@v2
        with:
          path: ./opencv-install
          key: ${{ runner.os }}-opencv-cache
      - name: Install OpenCV
        uses: rayandrews/with-opencv-action@v1
        with:
          dir: ./opencv-install
          cached: ${{ steps.opencv-cache.outputs.cache-hit }}
          opencv-version: '3.4.16'

      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: clean build test

